/**
 * Loads the lib/i18n/en.ts file as generated by formatjs extract
 * and formats it to be used in the app
 */

const fs = require("fs");
const path = require("path");

const enTsPath = path.join(__dirname, "../lib/i18n/en.ts");
const enTsContent = fs.readFileSync(enTsPath, "utf8");

// Load as JSON
const enJson = JSON.parse(enTsContent) as Record<
  string,
  { defaultMessage: string }
>;

// Replace `[key]: { defaultMessage: ... }` with `[key]: string`
const enJsonFormatted = Object.fromEntries(
  Object.entries(enJson).map(([key, value]) => [key, value.defaultMessage])
);

// Write to lib/i18n/messages.ts
fs.writeFileSync(
  enTsPath,
  `export const MessagesEn = ${JSON.stringify(enJsonFormatted, null, 2)};`
);
